[tool.poetry]
name = "my-project"
version = "0.1.0"
description = "HomeTask_01"
authors = ["Aleksandr <akovalenko881@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
